<div class="container" style="padding: 25px 25px 25px 25px">
	


<h4>Všeobecné podmínky autopůjčovny  BLACK ICE PRAGUE s.r.o . ke smlouvě o nájmu dopravního prostředku. </h2> 
  <br>
 
 
<h3>  1. ÚVODNÍ USTANOVENÍ </h3>
<p>1.1 Nájemcem se rozumí fyzická nebo právnická osoba, která má se společností uzavřenou smlouvu o nájmu dopravního prostředku. Nájemcem se rozumí i osoba uvedená v seznamu spolunájemců.</p>
 <p>1.2 Smlouvou o nájmu dopravního prostředku, jejíž evidenční číslo je uvedeno v záhlaví (dále jen „Smlouva“), se pronajímatel zavazuje poskytnout nájemci službu spočívající v pronájmu předmětného motorového vozidla (dále jen „předmětné vozidlo“) specifikovaného v příslušném znění smlouvy a ve specifikaci vozu a  protokolu o předání předmětného vozidla nájemci do užívání na dobu určitou, a to na dobu trvání nájmu. Za poskytnutí této služby se nájemce zavazuje splácet řádně splátky v souladu se Smlouvou a splátkovým kalendářem či jiným daňovým dokladem vystaveným společností.
 <p> 1.3 Smlouva se skládá ze smluvního formuláře, který obsahuje číslo smlouvy, specifikaci smluvních stran a předmětného vozidla, část smluvních ujednání, splátkového kalendáře či jiného daňového dokladu a těchto obchodních podmínek. Součástí Smlouvy jsou i případné dodatky Smlouvy a další dokumenty, o kterých to Smlouva (resp. Všeobecné obchodní podmínky) stanoví.
 <p>1.4 Smlouva se stává platnou a účinnou dnem jejího uzavření. 
<p>1.5 Společností a pronajímatelem se rozumí  BLACK ICE PRAGUE s.r.o., IČO06848354, se sídlem Chlumova  199/22, Praha 3, 130 00, sp.zn. C 290080 vedená u Městského soudu v Praze. 
<p>1.6 Za společnost může jednat zmocněný zástupce, dále jako předávající. 

<h3> 2. PŘEVZETÍ VOZIDLA</h3>
 <p>2.1. Před převzetím předmětného vozidla je nájemce povinen ho prohlédnout a ověřit jeho přesnou identifikaci, zjistit úplnost dodávky včetně dokumentace a přezkoušet, zda předmětné vozidlo nemá technické nedostatky a zda je plně použitelné. Jestliže má předmětné vozidlo technické nedostatky nebo není-li pro zvlášť sjednaný účel vhodné, nájemce jej nesmí převzít. Výjimku tvoří převzetí ojetého vozidla, kde drobné nedostatky (například malá laková poškození) zaznamená předávající na předávacím protokolu a nájemce jej potvrdí svým podpisem.
 <p>2.2. S předmětným vozidlem je nájemci předáno osvědčení o technickém průkazu vozidla (malý technický průkaz), doklad o povinném ručení, dálniční známka pro ČR a zákonná povinná výbava. 
 <p>2.3. Předání a převzetí předmětného vozidla potvrdí smluvní strany podpisem předávacího protokolu, který je obsahovou součástí Smlouvy. 
 <p>2.4. Nájemce prohlašuje, že se před převzetím smlouvy seznámil s Normami opotřebení a poškození vozu pro pronájem vozu, a že s nimi souhlasí. 
 
<h3>3. Splátky a jiné platby</h3>
  <p>3.1 Případnou splátku nájemného hrazenou předem a první řádnou splátku je nájemce povinen uhradit před převzetím předmětného vozidla (před začátkem doby nájmu). Každá další měsíční splátka je splatná vždy každý první den následujícího kalendářního měsíce, není-li ve splátkovém kalendáři či jiném daňovém dokladu vystaveném společností stanoveno jinak.
  <p>3.2 Nájemce je povinen platit všechny splátky včas a v dohodnuté výši s uvedením variabilního symbolu přiděleném společností, to vše na účet stanovený ve smlouvě.
  <p>3.3 Nájemce je povinen platit sjednané splátky i v době, kdy předmětné vozidlo z jakýchkoliv důvodů nemůže užívat, a to i tehdy, pokud došlo k jeho poškození, zničení a pojišťovna dosud nekonstatovala totální škodu předmětného vozidla, popř. odcizení a policie doposud nekonstatovala odcizení předmětného vozidla, neukončila či nepřerušila (neodložila) pátrání po odcizeném předmětném vozidle, nedohodnou-li se smluvní strany jinak. 
  <p>3.4 Veškeré jednorázové pohledávky společnosti vůči nájemci jsou splatné do ……… dnů od výzvy k zaplacení nebo vystavení faktury, není-li výslovně stanoveno jinak. 
  <p>3.5 Společnost je oprávněna nárokovat v případě prodlení nájemce se zaplacením jakékoliv platby podle Smlouvy smluvní pokutu ve výši 0,05 % z dlužné částky za každý započatý den prodlení. Kromě smluvní pokuty podle předchozí věty má společnost vůči nájemci právo na náhradu prokazatelných výloh spojených s vymáháním pohledávky, čímž není dotčena platnost ustanovení bodu 15.10.  

<h3>4. Kauce </h3>
<p>4.1 Při pronájmu vozidla je pronajímatel oprávněn vyžadovat od nájemce vratnou kauci ve výši 10 000 – 60 000,-Kč dle typu vozidla,  jako garanci za případné závazky plynoucí z nájmu vozidla nájemcem. 
<p> 4.2 Výše kauce je určena v závislosti na aktuální ceně konkrétního předmětu nájmu.
 <p> 4.3 Vratná kauce bude uhrazena v hotovosti nebo platební kartou před předáním vozidla nájemci a následně zúčtována po vrácení vozidla pronajímateli. Složením kauce není dotčena povinnost nájemce platit nájemné. Pronajímatel je oprávněn vůči složené záloze započíst veškeré své peněžité pohledávky za nájemcem vyplývající z uzavřené Smlouvy (např. neuhrazené nájemné, škody, nedotankování paliva, další ujeté kilometry nad denní či měsíční limit kilometrů, mytí a čištění auta atd.) 
 
<h3>5. Práva a povinnosti nájemce</h3>
 <p>5.1 Nájemce je povinen zabezpečit vozidlo proti odcizení, zneužití nebo poškození. Zejména je povinen při opuštění vozidla neponechávat uvnitř vozidla jakákoli ležící zavazadla nebo jiné předměty, které by mohly být podnětem k vniknutí třetí osoby do vozidla, neponechávat uvnitř vozidla jakékoli dokumenty k vozidlu (technický průkaz, doklady o zákonném pojištění, klíče atd.) a vozidlo uzamknout. 
 <p>5.2 Nájemce je povinen v případě vzniku jakékoliv pojistné události poskytnout veškerou součinnost, zejména se zavazuje jakoukoliv pojistnou událost nahlásit Policii příslušného státu, vyplnit formulář „Záznam o dopravní nehodě“ a zajistit další potřebné dokumenty vztahující se k vzniklé škodě s tím, že je povinen o pojistné události neprodleně informovat pronajímatele. Při nesplnění této povinnosti je nájemce povinen uhradit pronajímateli případný postih ze strany pojišťovny. V případech, kdy se zákonné nebo havarijní pojištění nevztahuje na krytí vzniklé škody způsobené nájemcem v plném rozsahu, je nájemce povinen zaplatit nekrytou část škody a v případech, kdy se pojištění na krytí vzniklých škod nevztahuje vůbec, je nájemce odpovědný za celou výši škody.
  <p>5.3 Nájemce je povinen oznámit pronajímateli bez zbytečného odkladu veškeré závady, které se na vozidle během jeho užívání projeví a vyžadují opravu. Pokud tuto povinnost nájemce nesplní, odpovídá za škody tím způsobené a ztrácí nároky, které mu jinak příslušely pro nemožnost nebo omezenou možnost užívat vozidlo pro vady. Náklady spojené s opravou nese pronajímatel, kromě těch případů, kdy potřeba opravy vznikla v důsledku nesprávného užívání vozidla nájemcem nebo v rozporu s obvyklým způsobem používání anebo porušením podmínek smlouvy ať už nájemcem nebo osobami, kterým nájemce umožnil k vozidlu přístup.
  <p>5.4 Nájemce není oprávněn bez předchozího písemného souhlasu pronajímatele používat vozidlo pro účely taxislužby, autopůjčovny nebo autoškoly, zúčastňovat se s vozidlem závodů, používat vozidlo k tlačení nebo vlečení automobilů, přívěsů nebo jiných předmětů, popřípadě předat vozidlo do užívání třetím osobám a cestovat mimo )zemí ČR. Za třetí osobu se pro účely tohoto ustanovení nepovažují zaměstnanci nájemce a jejích rodinné příslušníky. Nájemce není oprávněn bez předchozího písemného souhlasu pronajímatele provádět na vozidle jakékoliv úpravy či změny, včetně umístění reklamy.
  <p>5.5 Nájemce bere na vědomí, že pro případ nezaplacení nájemného, jiných nákladů spojených s pronájmem, při porušení smluvních podmínek nebo při vyčíslení nákladů převyšující hodnotu kauce, za které objektivně odpovídá nájemce, je pronajímatel oprávněn předmětné vozidlo dálkově zablokovat a následně odebrat. 
 <p>5.6 Nájemce je oprávněn v době trvání nájmu překročit aktuální celkový limit najetých km 300 km na území ČR) vzhledem k aktuálnímu období nájmu maximálně o 50% svého měsíčního tarifu. V případě porušení této povinnosti pronajímatel má právo požadovat  neprodlenou úhradu km nad povolený limit. 
  <p>5.7 V případě překročení celkového limitu km je nájemce povinen doplatit rozdíl o který sjednaný limit km převýšil a to vynásobením počtu překročených km s cenou za 1km nad limit sjednaný ve Smlouvě. 
 
<h3>6. Práva a povinnosti pronajímatele</h3>
 <p>6.1 Pronajímatel je povinen pojistit vozidlo pro případ poškození nebo zničení v důsledku havárie, poškození nebo zničení v důsledku živelné události, pro případ odcizení vozidla s územním rozsahem ČR a ostatní evropské země, včetně pojištění sedadel. Pronajímatel nenese odpovědnost za věci ponechané ve vozidle ani za škody způsobené osobám přepravovaným na ostatních sedadlech vozidla. 
 <p>6.2 Pronajímatel je povinen zajistit v plném rozsahu servis vozidla. Servisem se pro účel této smlouvy rozumí provádění pravidelných garančních a po garančních prohlídek dle servisního plánu a preventivní prohlídky vozidla nejméně jedenkrát za šest měsíců nebo každých 15 000 km.
  <p>6.3 Pronajímatel je oprávněn kdykoliv zkontrolovat stav, umístění a způsob užívání vozidla, a to i bez předchozího oznámení kontroly. Nájemce uděluje pronajímateli svolení k  přístupu k vozidlu za účelem kontroly stavu, umístění a způsobu užívání vozidla.
  <p>6.4 Pronajímatel je oprávněn provádět prostřednictvím GPS lokátoru umístěného ve vozidle kontrolu pohybu vozidla, rychlost a body zastavení. Údaje zjištěné prostřednictvím GPS lokátoru považují účastníci této smlouvy za závazné.

<h3>7. Cesty do zahraničí</h3>
  <p>7.1 Použít vozidlo pro cestu do Bulharska, Rumunska a zemí mimo Evropskou Unii je nájemce oprávněn pouze s písemným souhlasem pronajímatele. V případě, že nájemce s vozidlem cestuje do výše uvedených zemí bez souhlasu pronajímatele, bude vozidlo považováno za odcizené a tato skutečnost bude nahlášena Policii ČR. V takovém případě je nájemce povinen uhradit pronajímateli smluvní pokutu ve výši 10.000,- Kč a všechny náklady spojené s navracením vozidla. Pronajímatel je v takovém případě oprávněn vozidlo zastavit, zabránit vozidlu v další jízdě a od smlouvy o nájmu dopravního prostředku s okamžitou účinností odstoupit.
  <p>7.2 Nájemce není oprávněn cestovat s vozidlem do zemí bývalé Jugoslávie (kromě Chorvatska a Slovinska), bývalého Sovětského svazu, Albánie, Bulharska, Rumunska, Běloruska a Ukrajiny. ……
 
<h3>8. MAJETKOVÁ A JINÁ PRÁVA K VOZIDLU </h3>
  <p>8.1 Společnost je výlučným vlastníkem předmětného vozidla. Předáním předmětného vozidla uděluje společnost nájemci právo užívat předmětné vozidlo v souladu s právními předpisy České republiky, po dobu a za podmínek stanovených Smlouvou a těmito obchodními podmínkami.
  <p>8.2 Nájemce nesmí předmětné vozidlo zcizit či s předmětným vozidlem jinak disponovat v rozporu s účelem Smlouvy (např. prodat, zastavit, darovat, pronajmout, zapůjčit třetí osobě), kromě zapůjčení vozidla k jízdám svých zaměstnanců, statutárních orgánů nebo členů statutárního orgánu, anebo zapůjčení osobě blízké včetně družky a druha, je-li nájemcem fyzická osoba. Nájemce nese plnou odpovědnost za případné škody na předmětném vozidle vzniklé v souvislosti s jednáním třetí osoby. 
 <p>8.3 Nájemce se musí zdržet jakéhokoliv jednání, které by mohlo vést ke vzniku práv třetích osob k předmětnému vozidlu. Nájemce je povinen společnosti okamžitě ohlásit uplatnění nároků třetích osob na předmětné vozidlo, odcizení předmětného vozidla, poškození se škodou vyšší než 30.000 Kč a ztrátu předmětného vozidla. Nájemce nese náklady na obranu (ochranu) proti prosazování nároků třetích osob, ledaže byly zaviněny společností.
 8.4 Dodatečné úpravy, vestavby nebo jiná zhodnocení předmětného vozidla smí nájemce provést jen na základě písemného souhlasu společnosti. 
 <p>8.5 Nedodrží-li nájemce ustanovení uvedené v předcházejícím odstavci, je povinen nahradit společnosti způsobenou škodu. V takovém případě má společnost právo uplatnit vůči nájemci smluvní pokutu ve výši 100% částky, o níž byla hodnota předmětného vozidla úpravou změněna. Tímto není dotčeno právo společnosti na náhradu škody.
  <p>8.6 Předmětné vozidlo nesmí být použito jiným než běžným způsobem, tj. nesmí být použito např. k rychlostní jízdě, soutěžení, půjčení, přepravě nebezpečných látek, k trestné činnosti nebo cvičným jízdám. Nájemce plně odpovídá za škodu způsobenou použitím předmětného vozidla způsobem jiným než běžným. V případě opakovaného porušení daného bodu pronajímatel má právo ponechat kauci v plné výší. 
  <p>8.7 Nájemce není oprávněn k technickým zásahům na předmětném vozidle kromě běžné údržby dle instrukcí výrobce (výměna žárovek apod.). K technickým zásahům jsou oprávněny pouze servisy autorizované výrobcem nebo dovozcem předmětného vozidla dané značky. 
  <p>8.8 Nájemce je povinen před každým použitím předmětného vozidla překontrolovat jeho technický stav, a to včetně „kontrolek“ na přístrojové desce. Zjištěné závady je povinen neprodleně odstranit sám, pokud jejich povaha neodporuje omezením stanoveným v této smlouvě. V opačném případě je nájemce povinen závady odstranit prostřednictvím autorizovaného servisu nebo dle pokynů pronajímatele. 
 <p>8.9 Nájemce hradí veškeré pokuty udělené příslušnými orgány policie či státní správy v souvislosti s používáním předmětného vozidla v rozporu s příslušnými předpisy. Pokud je v takovém případě pokutována přímo společnost jako provozovatel vozidla, je společnost oprávněna náklady vynaložené na pokutu a případná řízení před příslušnými orgány přeúčtovat nájemci. Nájemce je povinen vést evidenci, kdo a kdy předmětné vozidlo řídil. Pokud je společnost vyzvána orgánem Policie či státní správy k identifikaci řidiče vozidla v okamžiku spáchání dopravního přestupku, je nájemce povinen společnosti, na její výzvu, sdělit identitu řidiče. 
  <p>8.10 Společnost neodpovídá za škodu či ušlý zisk nájemce, či jiné osoby v souvislosti s příp. nemožností dočasně či trvale užívat předmět nájmu. 
 
<h3>9. ODPOVĚDNOST ZA VADY A ZA ŠKODY NA PŘEDMĚTNÉM VOZIDLE</h3>
 <p>9.1 Za zničení, ztrátu, poškození a znehodnocení předmětného vozidla nebo jeho vybavení, které nejsou kryty podmínkami pojistné smlouvy, odpovídá nájemce společnosti objektivně, tzn. bez ohledu na míru jeho zavinění, avšak nikoliv při zavinění společnosti. 
 <p>9.2 V případě poruchy fungování počítače ujetých kilometrů upozorní nájemce bez prodlení, nejpozději však od 24 hodin, na tuto skutečnost společnost a nechá tuto závadu bezodkladně odstranit. Nájemce nesmí měnit údaje či jinak zasahovat do počítače ujetých kilometrů. Za přímé a nepřímé škody a ušlý zisk vzniklý nájemci nebo jiným osobám použitím předmětného vozidla, přerušením jeho použití, nebo jeho odejmutím odpovídá společnost nájemci jen tehdy, jestliže byly způsobeny opomenutím povinností společnosti vyplývajících ze Smlouvy či těchto obchodních podmínek.

<h3>10. ÚDRŽBA A SERVISNÍ NÁKLADY</h3>
 <p>10.1 Do výše specifikované údržby se nezapočítávají především následující položky, které si nájemce hradí sám anebo mu budou společností přeúčtovány/proplaceny: - Oprava a výměna náhradních dílů poškozených při nehodě, v důsledku nedbalosti, neoprávněného používání nebo nedodržení návodů a doporučení výrobce (např. nedodržení plánu údržby, použití nevhodných pohonných hmot nebo nemrznoucí směsi, nedoplňování předepsané hladiny oleje a nemrznoucí směsi, promeškání záruky apod.); pokud jsou tyto položky kryty pojistkou, společnost odečte nájemci od nákladů za opravu pojistné plnění vyplacené pojišťovnou; - Náklady na opravy dílů, které byly do vozu nainstalovány dodatečně bez vědomí společnosti; - Náklady vzniklé nepřiměřeným nebo nadměrným používáním předmětu nájmu; - Náklady spojené se ztrátou klíčů nebo dálkového ovládání; 
- Náklady na výměnu světlometů nebo skel, pokud tyto nehradí pojišťovna; - Náklady na opravy prováděné za speciální tarify nebo mimo běžnou pracovní dobu na žádost nájemce; - Náklady na odtahovou službu vzniklé v důsledku havárie, nedbalosti nebo neoprávněného používání předmětu nájmu, pokud tyto nejsou kryty asistenční službou nebo pojišťovnou; - Mytí, voskování a úklid interiéru. 
 <p>10.2 Společnost si vyhrazuje právo odmítnout po konzultaci s nájemcem neekonomické opravy předmětného vozidla. V takovém případě je společnost oprávněna Smlouvu vypovědět. 

<h3>11. PŘEDČASNÉ (MIMOŘÁDNÉ) UKONČENÍ SMLOUVY A JEJÍ FINANČNÍ VYPOŘÁDÁNÍ</h3>
  <p>11.1 Smlouva může být předčasně ukončena oboustrannou dohodou mezi nájemcem (nájemci) a pronajímatelem, v případě prokázaného odcizení předmětného vozidla, prokázaného úplného zničení předmětného vozidla, v případě úmrtí nájemce nebo dohodou smluvních stran na žádost nájemce. Společnost je oprávněna Smlouvu vypovědět, pokud nájemce závažným způsobem nebo opakovaně porušil či porušuje podmínky Smlouvy. Za závažné porušení Smlouvy se považuje například prodlení nájemce s platbami podle Bodu 3.2. Společnost je oprávněna Smlouvu dále vypovědět rovněž v případě, že na majetek nájemce je prohlášena insolvence nebo v případě, že nájemce závažným způsobem porušuje své povinnosti z jakéhokoli jiného závazkového vztahu mezi ním a společností. Smlouva je předčasně ukončena dnem účinnosti výpovědi. Výpověď je účinná předáním nebo doručením nájemci. Je-li výpověď předána i doručena, a to v různých dnech, je účinná dnem, který nastane dříve. Není-li možné výpověď předat ani doručit na poslední nájemcem písemně oznámenou adresu, platí, že byla doručena pátý pracovní den po odeslání.
  <p>11.2 V případě ukončení Smlouvy podle bodu 11.1 je nájemce povinen společnosti zaplatit: a) všechny do té doby splatné a neuhrazené peněžité závazky včetně jejich příslušenství, b) náklady spojené s odebráním a přepravou vozidla,  c) dohodnuté smluvní pokuty a příslušenství všech pohledávek, d) rozdíl mezi sumou za poskytnuté služby, které společnost v souladu se sjednanými podmínkami uhradila a sumou za poskytnuté služby uhrazenou nájemcem společnosti k datu ukončení smlouvy.
  <p>11.3 V případě prokázaného odcizení předmětného vozidla končí Smlouva dnem, v němž bylo společnosti doručeno usnesení o zahájení trestního stíhání určité osoby, odložení věci nebo jiné potvrzení vydané orgány činnými v trestním řízení o tom, že nelze vést trestní stíhání proti konkrétní osobě (neznámý pachatel), nedohodnou-li se smluvní strany na datu ukončení smlouvy jinak. Výše uvedené platí vždy pouze v případě, že nebylo vozidlo nalezeno a vráceno nájemci. 
  <p>11.4 Při úplném zničení předmětného vozidla (totální havárie) končí Smlouva dnem, v němž společnost obdržela potvrzení pojišťovny nebo soudního znalce o úplném zničení předmětného vozidla, nedohodnou-li se smluvní strany na datu ukončení Smlouvy jinak. 
 <p>11.5 V případě ukončení Smlouvy podle bodů 11.1 a 11.2 použije společnost pojistné plnění k úhradě škody vzniklé společnosti jako vlastníku předmětného vozidla. Pojistné plnění bude dále použito na úhradu závazků vyplývajících z bodů 11.1 a 11.2, a nájemce je povinen společnosti zaplatit: 
 a) všechny do té doby splatné a neuhrazené peněžité závazky včetně jejich příslušenství,
 b) náklady spojené s přepravou, skladováním, oceněním, pojištěním a prodejem zbytků předmětného vozidla,
 c) dohodnuté smluvní pokuty a příslušenství všech pohledávek,
společnost v souladu se sjednanými pojistnými smlouvami uhradila nebo je povinna uhradit pojistiteli, a sumou tohoto pojistného uhrazenou nájemcem společnosti k datu ukončení smlouvy, a to i v případě, kdy byla smlouva uzavřena v rámci obchodní akce, v rámci které bylo nájemci poskytnuto pojištění zdarma
e) rozdíl mezi sumou za poskytnuté služby, které společnost v souladu se sjednanými podmínkami uhradila a sumou za poskytnuté služby uhrazenou nájemcem společnosti k datu ukončení smlouvy, 
f) spoluúčast ve výši 5% (nejméně však 5.000 Kč) z pořizovací ceny vozu.
  <p>11.6 V případě kdy nájemce požaduje předčasné ukončení Smlouvy dohodou, zavazuje se informovat o tom společnost písemnou formou minimálně 10 dnů před požadovaným datem ukončení Smlouvy. Dohodou smluvních stran na žádost nájemce končí Smlouva dnem platnosti a účinnosti dohody. Společnost však není povinna na dohodu o ukončení Smlouvy přistoupit.
  <p>11.7 V případě ukončení Smlouvy podle bodu 11.6 je nájemce povinen společnosti zaplatit:
  a) všechny do té doby splatné a neuhrazené peněžité závazky včetně jejich příslušenství,
 b) náklady spojené s přepravou, skladováním, oceněním, pojištěním a prodejem předmětného vozidla,
 c) dohodnuté smluvní pokuty a příslušenství všech pohledávek.
 <p>11.8 V případě předčasného ukončení Smlouvy ze strany společnosti má společnost právo ponechat si kauci v celé výši jako náhradu ušlého zisku. Tím není dotčeno právo společnosti požadovat úhradu všech nákladů spojených s provozem vozidla a jeho řádnou údržbou.  
 <p>11.9 Pokud je nájemce v prodlení s úhradou pohledávky nezaplacené do dne předčasného ukončení smlouvy nebo pohledávky (nároku společnosti), která vznikla po předčasném ukončení Smlouvy nebo jako jeho důsledek, má společnost právo na úrok z prodlení ve výši 0,05% z dlužné částky za každý den prodlení ode dne splatnosti těchto pohledávek. Není-li podle obecně závazného právního předpisu možné výši úroku z prodlení sjednat tak, jak je uvedeno v předchozí větě, je výše úroku stanovena obecně závazným právním předpisem.  
 
<h3>12. TRVÁNÍ SMLOUVY A JEJÍ ŘÁDNÉ UKONČENÍ</h3>
  <p>12.1 Smlouva je uzavřena na dobu určitou a končí uplynutím doby nájmu. Tím není dotčeno právo pronajímatele vymáhat po nájemci úhradu všech nezaplacených závazků po ukončení této Smlouvy. 12.2 V případě, že skutečný jízdní výkon (tj. ujeté km dle tachometru k datu ukončení Smlouvy) při předání předmětu nájmu nájemcem bude vyšší, než byl stanoven dohodou nájemce a pronajímatele, a to včetně případné volné hranice km stanovené Smlouvou, je nájemce povinen zaplatit poplatek uvedený ve Smlouvě za každý km ujetý nad stanovený limit.  
 
<h3> 13. SMLUVNÍ POKUTY</h3>
  <p>13.1 Nájemce je povinen uhradit pronajímateli níže uvedené smluvní pokuty, a to za každé jednotlivé poškození vozu: 
     <p>a) propálení sedadla a/nebo dalších části interiérů: 30.000,- Kč 
         <p>b) trvalé znečištění sedadla: 10.000,- Kč, 
            <p> c) silné znečištění interiéru vozu, které je nutno odstranit profesionálním čištěním: 3.000,- Kč,
           <p>   d) znečištění karoserie: 1.500,- Kč 
            <p>  e) poškození plechového disku: 2.500,-Kč 
            <p>  f) poškození poklice: 500,- Kč  
            <p>  g) znečištění interiéru vozu, které není nutno odstranit profesionálním čištěním:: 300,-Kč  
            <p>  h) kouření v autě: 2000,- Kč  
            <p>  i) V případě ztráty příslušenství a součástí vozidla (např. technický průkaz, doklad o zákonném pojištění, klíče, poškození nebo ztráta registrační značky atd.) bude nájemci účtována smluvní pokuta dle reálných nákladů a do maximální výše 7000,- Kč. 
            <p>  j) V případě, že nájemce či další řidič při jízdě vozidlem překročí nejvyšší rychlost uvedenou v technickém průkazu vozidla, je nájemce povinen uhradit pronajímateli smluvní pokutu ve výši rovnající se výši nájemcem složené kauce. 
              <p>k) administrativní poplatek za dotankování pohonných hmot: 100,- Kč 
 <p>13.2.  Nárok pronajímatele na náhradu škody není úpravou smluvní pokuty dotčen. 
 
<h3>14. VRÁCENÍ PŘEDMĚTNÉHO VOZIDLA </h3>
 <p>14.1 Pokud uplyne doba nájmu, nebo pokud je Smlouva předčasně ukončena nebo vypovězena, je nájemce, případně jeho právní nástupce, povinen bez zbytečného odkladu přistavit předmětné vozidlo k dohodnutému místu, pokud společnost či její zmocněnec neurčí místo přistavení jinak, nestalo-li se tak již dříve. Nájemce je povinen předat spolu s předmětným vozidlem jeho dokumentaci (např. servisní knihu, návod k obsluze), soubor dokumentace řidiče, všechny klíče od předmětného vozidla. Nájemce odpovídá za předmětné vozidlo až do okamžiku, kdy je předmětné vozidlo řádně předáno společnosti nebo jí zmocněnému zástupci. V opačném případě bude nájemce povinen uhradit společnosti náklad na pořízení chybějícího příslušenství a dokumentů, případně poplatek za jednotlivé nevrácené dokumenty, příslušenství a vícenáklady. Kromě úhrady výše uvedených nákladů má Společnost právo za porušení povinností dle tohoto odstavce uplatnit vůči nájemci smluvní pokutu ve výši 10.000,-Kč.
  <p>14.2 Nájemce je povinen předmětné vozidlo navrátit ve stavu odpovídajícím počtu najetých km podle pokynů, které nájemce obdržel při převzetí vozidla. Společnost nebo jí zplnomocněný zástupce zkontroluje celkový stav vozidla. Nevrátí-li nájemce vozidlo ve stavu odpovídajícím předání a počtu najetých km, je povinen uhradit náklady vynaložené na uvedení vozidla do takovéhoto stavu. V případě, že nedojde ke shodě o stavu a poškození vozidla a z toho plynoucího rozpočtu oprav, popř. snížení zůstatkové ceny, určí společnost nezávislého znalce. Stanovisko znalce je pro obě strany závazné. Náklady na vyhotovení znaleckého posudku nese strana, jejíž stanovisko nebylo správné. Předmětné vozidlo se považuje za řádně vrácené okamžikem podpisu protokolu o převzetí předmětného vozidla oběma stranami. 
  <p>14.3 Předmětné vozidlo je nájemce povinen vrátit se stejným obsahem pohonných hmot v nádrži s jakým bylo vozidlo převzato v okamžiku výpůjčky. V opačném případě je účtován administrativní poplatek za dotankování pohonných hmot uvedený v bodě 13.1. písm. k) a náhrada hmot podle aktuálních cen paliva.
  <p>14.4 Nepřistaví-li nájemce předmětné vozidlo, ačkoli je k tomu podle Smlouvy povinen, jsou společnost, případně její zmocněnec, oprávněni předmětné vozidlo zajistit a odebrat nájemci. Zajištěním vozidla se rozumí taktéž jeho dálkové zablokování (blokace řídící jednotky) prostřednictvím elektronických systémů. Společnost má v takovém případě právo uplatnit vůči nájemci smluvní pokutu až do výše složené kauce, 1000,- kč za každou započatou hodinu, po smluvně zapsaném předpokládaném předání vozidla.
 <p>14.5 Pokud nájemce nevrátí předmětné vozidlo do dvou dnů ode dne, kdy mu povinnost vrátit vozidlo vznikla, je povinen uhradit pronajímateli smluvní pokutu ve výši  odpovídající ceně nájmu předmětného vozidla za 1 den a to dle aktuálního ceníku vystavěného na internetových stránkách pronajímatele. V případě, že předmětné nebo obdobné vozidlo v ceníku pronajímatele není uvedeno, odpovídá smluvní pokuta ve výši odpovídající ceně pronájmu za nejdražší automobil stejné kategorie, v jaké se nachází předmětné vozidlo.  
 
 <p>14.6 Pokud a) nájemce vrátí vozidlo zatížené právní vadou bránící neomezené dispozici s vozidlem, kterou nezavinila společnost, nebo  b) dojde k vážnému poškození, zničení či odcizení vozidla, které není kryto pojistným plněním z důvodu pochybení na straně nájemce (nezajištění pojištění v požadovaném rozsahu, zkrácení či odepření výplaty pojistného plnění z důvodu porušení právní povinnosti nájemce, apod.) a které znemožňuje vrácení vozidla v řádném stavu, c) nájemce vrátí vozidlo ve stavu, který neumožňuje další použitelnost vozu pro podnikání společnosti (zejména pokud dojde ke ztrátě servisní záruky nebo záruky mobility, či pokud bylo vozidlo závažně poškozeno, zničeno či odcizeno z důvodu pochybení na straně nájemce, je společnost oprávněna nárokovat vůči nájemci smluvní pokutu ve výši ceny předmětného vozidla. Při jeho převzetí nájemcem. Společnost má právo výši svého nároku uplatněného v souladu s tímto odstavcem snížit až na náhradu skutečně vzniklé škody. 
 <p>14.7 Veškeré náklady společnosti na odebrání předmětného vozidla (včetně případných nákladů společnosti na vymáhací agenturu) jdou k tíži nájemce a společnost má právo je uplatnit vůči nájemci. Tyto náklady mohou být zahrnuty v případě předčasného ukončení smlouvy mezi ostatní náklady do finančního vypořádání Smlouvy.
  14.8 Jsou-li zároveň s odebraným předmětným vozidlem zajištěny věci, které jsou spojeny s předmětným vozidlem a lze je považovat za součást nebo příslušenství předmětného vozidla, považují se za majetek společnosti a nájemce nemá při vrácení předmětného vozidla nárok na jejich úhradu. 

<h3>15. ZÁVĚREČNÁ USTANOVENÍ</h3>
  <p>15.1 Nájemce je povinen ohlásit společnosti písemně do 14 dnů změnu důležitých údajů o své osobě, zejména změnu adresy, jména či názvu společnosti, bankovního konta, ze kterého jsou platby prováděny, zánik společnosti, její splynutí či sloučení s jinou společností, jakékoli jiné změny v obchodním rejstříku, vstup do insolvenčního řízení, apod. Nájemce odpovídá za to, že společnost má vždy k dispozici jeho přesnou adresu pro doručování pošty. 
 <p>15.2 Žádným ustanovením těchto obchodních podmínek o smluvní pokutě není dotčeno právo společnosti na náhradu škody vzniklé společnosti v důsledku porušení Smlouvy nájemcem.
 <p> 15.3 Všechna smluvní ujednání a veškeré změny Smlouvy musí mít písemnou formu.
  <p>15.4 Pro spory vzešlé ze Smlouvy je příslušný soud v místě sídla společnosti pronajímatele.
 <p>15.5 Smluvní strany se dohodly, že právní vztah založený Smlouvou se řídí občanským zákoníkem v platném znění.
 <p> 15.6 Nájemce je srozuměn a souhlasí s tím, že společnost je oprávněna prověřovat skutečnosti týkající se jeho právní subjektivity, právních a vlastnických poměrů a ekonomické bonity. 
 <p>15.7 Nájemce (je-li fyzickou osobou) prohlašuje, že si je vědom svých práv týkajících se ochrany jeho osobních údajů vyplývajících z obecně závazných právních předpisů, zejména zákona č. 101/2000 Sb. Nájemce je srozuměn s tím, že údaje o jeho osobě (je-li fyzickou osobou), resp. údaje o jiných fyzických osobách, které od něj společnost získala, příp. získá, v souvislosti se sjednáním, uzavřením a správou Smlouvy, uchová ve své evidenci po dobu, po kterou je to nezbytné pro ochranu zájmů společnosti a účelné pro budoucí nabízení služeb společnosti a jejích obchodních partnerů, resp. po kterou to vyžadují obecně závazné právní předpisy, a že tyto údaje bude společnost využívat výlučně pro zajišťování svých obchodních potřeb, zejména pro účely spravování Smlouvy, pojištění související s předmětným vozidlem, nabízení dalších služeb (i po ukončení Smlouvy), příp. pro vymáhání pohledávky za nájemcem, přičemž uvedené služby pro společnosti zajišťují a budou zajišťovat jménem společnosti kromě jejích zaměstnanců rovněž třetí osoby (např. dodavatel, zasilatelské společnosti, pojišťovny, reklamní agentury, inkasní agentury, apod.). Nájemce je srozuměn s tím, že v případě, že závažným způsobem poruší Smlouvu nebo závazek z jiné smlouvy, je společnost oprávněna poskytnout tuto informaci spolu s jeho osobními údaji v nezbytném rozsahu třetím osobám, příp. ji zveřejnit, za účelem ochrany svých práv a oprávněných zájmů. Nájemce bere na vědomí, že některé jeho telefonické hovory s pracovníky společnosti mohou být nahrávány. 
 <p>15.8 Společnost je oprávněna kdykoli provést zápočet jakýchkoli peněžitých závazků a pohledávek, které ji vznikly za nájemcem, a to i tehdy, pokud vyplývají z různých právních vztahů.  
 <p>15.9 Společnost je oprávněna pověřit vymáháním jakékoliv pohledávky vůči nájemci vyplývající z této Smlouvy třetí subjekt. V případě vymáhání pohledávky třetím subjektem je nájemce povinen uhradit Společnosti smluvní pokutu ve výši 500 Kč za náklady spojené s každou písemnou, telefonickou či faxovou upomínkou, přičemž těchto upomínek může být nejvýše šest (6).Svým podpisem nájemce potvrzuje, že tyto obchodní podmínky tvoří nedílnou součást Smlouvy, kterou se společností  uzavírá a jejíž evidenční číslo je uvedeno v záhlaví. 
 
<p>15.10 Tyto Všeobecné obchodní podmínky jsou platné od  

</p>
</div>
</div>
</div>
<style>
footer 
{
    display: none !important;
  }  
    </style>
